name: onPush
#
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Get Weather
    steps:
      - uses: actions/checkout@v2
      - name: Get Weather
        shell: bash
        run: chmod +x ./src/getWeather.sh && ./src/getWeather.sh
        env:
          CI: true
          CITY: balıkesir
      - name: SMS text
        shell: bash
        run: chmod +x ./src/sendSms.sh && ./src/sendSms.sh
        env:
          CI: true
          API_KEY: ${{ secrets.API_KEY }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
          MSISDN_SENDER: ${{ secrets.MSISDN_SENDER }}
          MSISDN_RECEIVER: ${{ secrets.MSISDN_RECEIVER }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      # - name: 'Sending SMS Notification'
      #   uses: twilio-labs/actions-sms@v1
      #   with:
      #     fromPhoneNumber: ${{ secrets.MSISDN_SENDER }}
      #     toPhoneNumber: ${{ secrets.MSISDN_RECEIVER }}
      #     message: ${{$(cat sms.txt)}}"
      #   env:
      #     TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      #     TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
      #     TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: sms
          path: sms.txt
